/**
 * generated by Xtext
 */
package gama.core.lang.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSpecies</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.lang.gaml.GamlPackage#getD_Species()
 * @model
 * @generated
 */
public interface D_Species extends Statement
{
} // D_Species
