/**
 * generated by Xtext
 */
package gama.core.lang.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equation Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.lang.gaml.GamlPackage#getEquationDefinition()
 * @model
 * @generated
 */
public interface EquationDefinition extends GamlDefinition
{
} // EquationDefinition
