/**
 * generated by Xtext
 */
package gama.core.lang.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reserved Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.lang.gaml.GamlPackage#getReservedLiteral()
 * @model
 * @generated
 */
public interface ReservedLiteral extends TerminalExpression
{
} // ReservedLiteral
