/**
 * generated by Xtext
 */
package gama.core.lang.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SReflex</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.lang.gaml.GamlPackage#getS_Reflex()
 * @model
 * @generated
 */
public interface S_Reflex extends S_Declaration, VarDefinition
{
} // S_Reflex
