/**
 * generated by Xtext
 */
package gama.core.lang.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SString Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.lang.gaml.GamlPackage#getS_StringDefinition()
 * @model
 * @generated
 */
public interface S_StringDefinition extends S_Declaration
{
} // S_StringDefinition
