/**
 * generated by Xtext
 */
package gama.core.lang.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Skill Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.lang.gaml.GamlPackage#getSkillFakeDefinition()
 * @model
 * @generated
 */
public interface SkillFakeDefinition extends GamlDefinition
{
} // SkillFakeDefinition
