/*
 * generated by Xtext
 */
package ummisco.gama.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGamlScopeProvider extends DelegatingScopeProvider {
}
