/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.S_Global;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SGlobal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_GlobalImpl extends StatementImpl implements S_Global
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_GlobalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SGLOBAL;
  }

} //S_GlobalImpl
