/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.S_Loop;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SLoop</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_LoopImpl extends S_DeclarationImpl implements S_Loop
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_LoopImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SLOOP;
  }

} //S_LoopImpl
