/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.S_Other;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SOther</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_OtherImpl extends StatementImpl implements S_Other
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_OtherImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SOTHER;
  }

} //S_OtherImpl
