/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.speciesOrGridDisplayStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>species Or Grid Display Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class speciesOrGridDisplayStatementImpl extends StatementImpl implements speciesOrGridDisplayStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected speciesOrGridDisplayStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SPECIES_OR_GRID_DISPLAY_STATEMENT;
  }

} //speciesOrGridDisplayStatementImpl
