/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.TypeDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TypeDefinitionImpl extends GamlDefinitionImpl implements TypeDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.TYPE_DEFINITION;
  }

} //TypeDefinitionImpl
