/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.VarFakeDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Var Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VarFakeDefinitionImpl extends VarDefinitionImpl implements VarFakeDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarFakeDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.VAR_FAKE_DEFINITION;
  }

} //VarFakeDefinitionImpl
