/*
 * generated by Xtext
 */
package gama.core.lang.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class GamlProposalProvider extends AbstractGamlProposalProvider {
}
