/**
 * generated by Xtext
 */
package gama.core.lang.gaml.impl;

import gama.core.lang.gaml.ActionDefinition;
import gama.core.lang.gaml.GamlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ActionDefinitionImpl extends GamlDefinitionImpl implements ActionDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.ACTION_DEFINITION;
  }

} //ActionDefinitionImpl
