/**
 * generated by Xtext
 */
package gama.core.lang.gaml.impl;

import gama.core.lang.gaml.GamlPackage;
import gama.core.lang.gaml.IntLiteral;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Int Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntLiteralImpl extends TerminalExpressionImpl implements IntLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.INT_LITERAL;
  }

} //IntLiteralImpl
