/**
 * generated by Xtext
 */
package gama.core.lang.gaml.impl;

import gama.core.lang.gaml.GamlPackage;
import gama.core.lang.gaml.S_Declaration;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SDeclaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_DeclarationImpl extends StatementImpl implements S_Declaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_DeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SDECLARATION;
  }

} //S_DeclarationImpl
