/**
 * generated by Xtext
 */
package gama.core.lang.gaml.impl;

import gama.core.lang.gaml.GamlPackage;
import gama.core.lang.gaml.S_StringDefinition;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SString Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_StringDefinitionImpl extends S_DeclarationImpl implements S_StringDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_StringDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SSTRING_DEFINITION;
  }

} //S_StringDefinitionImpl
