/*
 * generated by Xtext
 */
package gama.core.lang.ide;

import org.eclipse.xtext.ide.editor.contentassist.IPrefixMatcher;
import org.eclipse.xtext.ide.editor.contentassist.IProposalConflictHelper;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AntlrProposalConflictHelper;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;

import com.google.inject.Binder;

import gama.core.lang.ide.AbstractGamlIdeModule;
import gama.core.lang.ide.contentassist.antlr.GamlParser;

/**
 * Use this class to register ide components.
 */
public class GamlIdeModule extends AbstractGamlIdeModule {

	/**
	 * @see org.eclipse.xtext.service.AbstractGenericModule#configure(com.google.inject.Binder)
	 */
	@Override
	public void configure(final Binder binder) {
		super.configure(binder);
		configureContentAssistLexer(binder);
		binder.bind(IContentAssistParser.class).to(GamlParser.class);
		binder.bind(IProposalConflictHelper.class).to(AntlrProposalConflictHelper.class);
		binder.bind(IPrefixMatcher.class).to(IPrefixMatcher.IgnoreCase.class);
	}
}
