/*
 * generated by Xtext
 */
package ummisco.gama.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ummisco.gama.GamlRuntimeModule;
import ummisco.gama.GamlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GamlIdeSetup extends GamlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GamlRuntimeModule(), new GamlIdeModule()));
	}
	
}
