/*
 * generated by Xtext
 */
package ummisco.gama;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GamlStandaloneSetup extends GamlStandaloneSetupGenerated {

	public static Injector doSetup() {
		return new GamlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

}
