/*
 * generated by Xtext
 */
package gama.core.lang.serializer;

import ummisco.gama.serializer.AbstractGamlSemanticSequencer;

public class GamlSemanticSequencer extends AbstractGamlSemanticSequencer {
}
