/*
 * generated by Xtext
 */
package gama.core.lang.serializer;

import ummisco.gama.serializer.AbstractGamlSyntacticSequencer;

public class GamlSyntacticSequencer extends AbstractGamlSyntacticSequencer {
}
