/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.gaml.GamlPackage#getActionFakeDefinition()
 * @model
 * @generated
 */
public interface ActionFakeDefinition extends ActionDefinition
{
} // ActionFakeDefinition
