/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.gaml.GamlPackage#getActionDefinition()
 * @model
 * @generated
 */
public interface ActionDefinition extends GamlDefinition
{
} // ActionDefinition
