/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equation Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.gaml.GamlPackage#getEquationFakeDefinition()
 * @model
 * @generated
 */
public interface EquationFakeDefinition extends EquationDefinition
{
} // EquationFakeDefinition
