/**
 * generated by Xtext
 */
package ummisco.gama.gaml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pragma</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gama.core.gaml.Pragma#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see gama.core.gaml.GamlPackage#getPragma()
 * @model
 * @generated
 */
public interface Pragma extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see gama.core.gaml.GamlPackage#getPragma_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link gama.core.gaml.Pragma#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Pragma
