/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SAction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.gaml.GamlPackage#getS_Action()
 * @model
 * @generated
 */
public interface S_Action extends S_Definition
{
} // S_Action
