/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SReflex</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.gaml.GamlPackage#getS_Reflex()
 * @model
 * @generated
 */
public interface S_Reflex extends S_Declaration
{
} // S_Reflex
