/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.gaml.GamlPackage#getStringLiteral()
 * @model
 * @generated
 */
public interface StringLiteral extends TerminalExpression
{
} // StringLiteral
