/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gama.core.gaml.GamlPackage#getTypeFakeDefinition()
 * @model
 * @generated
 */
public interface TypeFakeDefinition extends TypeDefinition
{
} // TypeFakeDefinition
