/*
 * generated by Xtext
 */
package gama.core.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GamlUiModule extends AbstractGamlUiModule {

	public GamlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
