/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.EquationFakeDefinition;
import ummisco.gama.gaml.GamlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Equation Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EquationFakeDefinitionImpl extends EquationDefinitionImpl implements EquationFakeDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EquationFakeDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.EQUATION_FAKE_DEFINITION;
  }

} //EquationFakeDefinitionImpl
