/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.S_Reflex;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SReflex</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_ReflexImpl extends S_DeclarationImpl implements S_Reflex
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_ReflexImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SREFLEX;
  }

} //S_ReflexImpl
