/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.S_Solve;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SSolve</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_SolveImpl extends StatementImpl implements S_Solve
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_SolveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SSOLVE;
  }

} //S_SolveImpl
