/**
 * generated by Xtext
 */
package ummisco.gama.gaml.impl;

import org.eclipse.emf.ecore.EClass;

import ummisco.gama.gaml.GamlPackage;
import ummisco.gama.gaml.VarDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Var Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VarDefinitionImpl extends GamlDefinitionImpl implements VarDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.VAR_DEFINITION;
  }

} //VarDefinitionImpl
