/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ummisco.gama.gaml.GamlPackage#getBooleanLiteral()
 * @model
 * @generated
 */
public interface BooleanLiteral extends TerminalExpression
{
} // BooleanLiteral
