/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Facet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ummisco.gama.gaml.Facet#getKey <em>Key</em>}</li>
 *   <li>{@link ummisco.gama.gaml.Facet#getExpr <em>Expr</em>}</li>
 *   <li>{@link ummisco.gama.gaml.Facet#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see ummisco.gama.gaml.GamlPackage#getFacet()
 * @model
 * @generated
 */
public interface Facet extends VarDefinition
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see ummisco.gama.gaml.GamlPackage#getFacet_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link ummisco.gama.gaml.Facet#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see ummisco.gama.gaml.GamlPackage#getFacet_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link ummisco.gama.gaml.Facet#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(Block)
   * @see ummisco.gama.gaml.GamlPackage#getFacet_Block()
   * @model containment="true"
   * @generated
   */
  Block getBlock();

  /**
   * Sets the value of the '{@link ummisco.gama.gaml.Facet#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(Block value);

} // Facet
