/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ummisco.gama.gaml.GamlPackage#getIntLiteral()
 * @model
 * @generated
 */
public interface IntLiteral extends TerminalExpression
{
} // IntLiteral
