/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SDeclaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ummisco.gama.gaml.GamlPackage#getS_Declaration()
 * @model
 * @generated
 */
public interface S_Declaration extends Statement, VarDefinition
{
} // S_Declaration
