/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SDirect Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ummisco.gama.gaml.GamlPackage#getS_DirectAssignment()
 * @model
 * @generated
 */
public interface S_DirectAssignment extends S_Assignment
{
} // S_DirectAssignment
