/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SLoop</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ummisco.gama.gaml.GamlPackage#getS_Loop()
 * @model
 * @generated
 */
public interface S_Loop extends S_Declaration
{
} // S_Loop
