/**
 * generated by Xtext
 */
package ummisco.gama.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SOther</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ummisco.gama.gaml.GamlPackage#getS_Other()
 * @model
 * @generated
 */
public interface S_Other extends Statement
{
} // S_Other
