/*
 * generated by Xtext
 */
package gama.core.lang;

import com.google.inject.Injector;

import ummisco.gama.GamlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GamlStandaloneSetup extends GamlStandaloneSetupGenerated {

	public static Injector doSetup() {
		return new GamlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

}
